@startuml Резалка комментов
hide empty description

state NotInComment
state InSinglelineComment
state MaybeMultilineCommentStarting
state InMultilineComment
state MaybeMultilineCommentEnding

[*] --> NotInComment

' Однострочные комменты
NotInComment --> InSinglelineComment : "";""
InSinglelineComment --> NotInComment : ""\\n""
note on link: Отдать текущий символ (""\\n"")

' Многострочные комменты
NotInComment --> MaybeMultilineCommentStarting : ""/""
note on link: Сохранить символ (""/"")
MaybeMultilineCommentStarting --> NotInComment : не ""*""
note on link: # Отдать сохранённый символ (""/"")\n# Cтереть сохранённый символ\n# Отдать текущий символ (не ""*"")
MaybeMultilineCommentStarting --> InMultilineComment : ""*""
note on link: Стереть сохранённый символ (""/"")
InMultilineComment --> MaybeMultilineCommentEnding : ""*""
MaybeMultilineCommentEnding --> NotInComment : ""/""
MaybeMultilineCommentEnding --> InMultilineComment : не ""/""

' Основной код (не коммент)
NotInComment -> NotInComment : не "";"" и не ""/""
note on link: Отдать текущий символ (не "";"" и не ""/"")
@enduml